### ISSUE TITLE
How to remove invalid sub-merchants

### ISSUE THREAD

**Issue by avalond** [braintree/braintree_node#118]
### General information

* SDK/Library version: 2.3.0
* Environment: sandbox
* Language, language version, and OS:  Node v8.6.0 on Mac version 10.13.1

How to remove invalid sub-merchants,i found create, update, find functions,but is not found remove(delete)，How do I remove an invalid sub-merchants that has invalid?

**Comment by crookedneighbor** [comment]
While we do not offer the ability to delete or deactivate sub-merchant accounts, you can always make them effectively inactive by not using them in transaction sale calls. 

This will allow you to no longer use these inactive merchant accounts, but would preserve whatever data is associated with them in your Braintree Gateway in the event you ever need to access it.

Since this is not SDK specific, I'm going to close this, but if you have more questions, feel free to reach out to our support team. https://developers.braintreepayments.com/forms/contact
