### ISSUE TITLE
Unit Testing

### ISSUE THREAD

**Issue by j** [braintree/braintree_node#123]
### General information

* SDK/Library version: Latest
* Environment: Testing
* Language, language version, and OS: Any

### Issue description

I'm wondering what the best way to run integration tests.  I'd prefer to not do remote HTTP calls and use something like nock, but it seems kind of like a pain to do so.

What are some recommendations?

**Comment by crookedneighbor** [comment]
You say `run integration tests` in your issue description, but the title says `Unit Testing` and the rest of the message sounds like unit testing to me, so I assume you meant `run unit tests` instead. If that's not correct, let me know.

One easy way would be to simply stub the methods you're calling with a stubbing library like sinon.

```js
const braintree = require("braintree")
const sinon = require('sinon')
const expect = require('chai').expect

const gateway = braintree.connect({
  environment: braintree.Environment.Sandbox,
  merchantId: 'any_value',
  publicKey: 'any_value',
  privateKey: 'any_value'
});

const fakeClientTokenResult = {
  clientToken: 'fake_client_token',
  success: true
}

sinon.stub(gateway.clientToken, 'generate').resolves(fakeClientTokenResult)

gateway.clientToken.generate().then((res) => {
  expect(res.success).to.equal(true)
  expect(res.clientToken).to.equal('fake_client_token')
})
```

You can do some manual testing in your sandbox to generate a fixture for the different calls you need for use when stubbing. 

Going to close this now, because I think this answers your question, but if you need additional help, feel free to comment here.
