### ISSUE TITLE
How to check if card is vbv or msc or amexsafekey?

### ISSUE THREAD

**Issue by juragandotid** [braintree/braintree_node#125]
Can i make function to check if card vbv or msc or amexsafekey?

if that card is vbv msc and amex safekey it's will redirect to verification vbv msc and amex safekey and when card isn't  vbv msc and amex safekey it will redirect to function proccess payment after that redirect payment success.

What the basicly code.

Thank you.

**Comment by crookedneighbor** [comment]
I assume you are referring to [3D Secure](https://developers.braintreepayments.com/guides/3d-secure/overview).

Here are the docs for collecting 3D Secure cards on your website: https://developers.braintreepayments.com/guides/3d-secure/client-side/javascript/v3

The basic idea is that you tokenize the card details with Hosted Fields or Drop-in and receive back a payment method nonce. You call `verifyCard` with the nonce, and if it is a 3D Secure card, the 3D Secure verification flow will start.

Since this is not an issue with the SDK, I'm going to close this issue. For further help with your integration, please contact our support team at https://articles.braintreepayments.com/forms/contact
