### ISSUE TITLE
Ping method not available

### ISSUE THREAD

**Issue by pfreixes** [braintree/braintree_node#131]
### General information

* SDK/Library version: all
* Environment: all
* Language, language version, and OS: all

### Issue description

The current library does not expose an explicit method to hit the `ping` endpoint of braintree to check the  availability of the service.

Correct me if i'm wrong but the following endpoint is a valid endpoint that can be used to check the availability: `https://www.braintreegateway.com/merchants/{merchant_id}/ping`.

**Comment by crookedneighbor** [comment]
You are free to use that endpoint, but it is not part of our publicly documented API.

We won't be adding it to the SDK, because if there is an availability problem, you'll get the exact same response from this endpoint as any of the other endpoints, so there's no real reason to add it to the SDK. You can always request the endpoint directly (it does not require authentication) if you wish.
