### ISSUE TITLE
Can we add customerId to the subscription response? 

### ISSUE THREAD

**Issue by madgeni** [braintree/braintree_node#145]
### General information

* SDK/Library version: 
* Environment: 
* Language, language version, and OS: 

### Issue description

I don't store, and so can't pass on my users first name + last name - can we please get the customerId added to the response, so that I can tie back subscription events to a customer?

Thanks

**Comment by madgeni** [comment]
stupid! rtfm :)

**Comment by mathieu-bour** [comment]
Not that stupid question, since according to the SDK documentation, you can only access to the name/phone/url (source: https://developers.braintreepayments.com/reference/response/subscription/php#descriptor.name)
In my project, I have to use the `paymentMethodToken`, then use the Customer Search method to retrieve the entire customer profile, including the precious email field.The method however, sound like a hack.
Is there any plan to add the `customerId` field ?

**Comment by crookedneighbor** [comment]
There are no plans at this time. To get this info, it'd be easiest for you to maintain your own association between customers and their subscriptions in your site's database. That would cut down on the calls needed to be made to the Braintree gateway.
