### ISSUE TITLE
Can't find variable: Symbol

### ISSUE THREAD

**Issue by ShridharCodewave** [braintree/braintree_node#155]
Iam trying to integrate paypal into my react native project and according to paypal documentation I need to integrate braintree to generate a "token" to initiate the payment. My code is as below and Iam getting the above error  in braintree\lib\braintree\transaction.js.

```
componentWillMount() {
    gateway = braintree.connect({
      environment: braintree.Environment.Sandbox,
      merchantId: "xxxx",
      publicKey: "xxxx",
      privateKey: "xxxx"
    });
  }
  buttonPress(token) {
    var clientToken = null
    gateway.clientToken.generate({}, function (err, response) {
      clientToken = response.clientToken
    });
    try {
      const {
        nonce,
        payerId,
        email,
        firstName,
        lastName,
        phone
      } = requestOneTimePayment(
        clientToken,
        {
          amount: '500', // required
          // any PayPal supported currency (see here: https://developer.paypal.com/docs/integration/direct/rest/currency-codes/#paypal-account-payments)
          currency: 'INR',
          // any PayPal supported locale (see here: https://braintree.github.io/braintree_ios/Classes/BTPayPalRequest.html#/c:objc(cs)BTPayPalRequest(py)localeCode)
          localeCode: 'zh_XC',
          shippingAddressRequired: false,
          userAction: 'commit', // display 'Pay Now' on the PayPal review page
          // one of 'authorize', 'sale', 'order'. defaults to 'authorize'. see details here: https://developer.paypal.com/docs/api/payments/v1/#payment-create-request-body
          intent: 'authorize',
        }
      );
    }
    catch (e) {
      Alert.alert(e);
    }
```
and the buttonPress() function is called on press of a button.

**Comment by crookedneighbor** [comment]
You should not use the server sdk from within a client (ie, the compiled iOS or Android app). That will leak your API keys to the client.

Instead, you must use the node sdk from a node server, so you'd make a request to that server to get the client token, rather than generating it from within the client. You could also use a [tokenization key instead](https://developers.braintreepayments.com/guides/authorization/tokenization-key/javascript/v3), but you'd still need a server to transact on the nonce.

The underlying reason why you're seeing this error is that the version of node or React Native you are using doesn't support [Symbols](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol).
