### ISSUE TITLE
deepErrors() returns empty array when a transaction fails

### ISSUE THREAD

**Issue by fabriziomoscon** [braintree/braintree_node#37]
I am causing a failing transaction using these arbitrary amounts:
https://developers.braintreepayments.com/ios+ruby/reference/general/testing#test-amounts-for-unsuccessful-transactions

but for any amount I try deepErrors returns an empty array

```JavaScript
// passing 2004
{ saleRequest: 
   { amount: 2004,
     merchantAccountId: '4tx62hp6hsrtzfkb',
     creditCard: 
      { number: '4111111111111111',
        cvv: '123',
        expirationMonth: '12',
        expirationYear: '2020' },
     customer: 
      { id: 1413310867389,
        firstName: 'Chris',
        lastName: 'example',
        email: 'chris@example.com' },
     options: { storeInVaultOnSuccess: true } } }

// log
result.errors.deepErrors() =>  []
```

from this list:
https://developers.braintreepayments.com/ios+ruby/reference/general/processor-response

I can see the correct error should be `Expired Card`, but nothing is returned

Only if I look into `result.transaction.processorResponseCode` I can find the correct error code

Note: deepErrors() works for error in `gateway.creditCard.create()` so one would expect it to work for any errors

**Comment by jdlc** [comment]
Hi @fabriziomoscon, thanks for raising this issue. You are correct that `deepErrors()` will only be populated in the case of a validation error, and that to get processor errors you will have to access the transaction result object. We're not planning to add any convenience methods to access the processor errors at this time.

We've updated the [code snippets for Node](https://developers.braintreepayments.com/node/reference/response/transaction#validation-errors) involving `deepErrors()` since you've raised this issue, and I hope you find them more clear.
