### ISSUE TITLE
Inaccurate duplicate error when creating payment method with discover test data

### ISSUE THREAD

**Issue by rkelly92** [braintree/braintree_node#57]
```
gateway.paymentMethod.create({
      customerId: args.braintreeId,
      paymentMethodNonce: args.nonce,
      options: {
        makeDefault: args.isPrimary,
        failOnDuplicatePaymentMethod: true
      }
    }
```
When trying to create a payment method in a sandbox environment, with the failOnDuplicatePaymentMethod option set as true, using `fake-valid-discover-nonce` or a nonce generated with the test Discover card number `6011111111111117` the process fails with the following: `Error: Duplicate card exists in the vault.`. However, said payment method is not previously stored in the user's vault (it even happens with new customers with no saved payment methods).

**Comment by crookedneighbor** [comment]
Hi @rkelly92,

The vault referred to in the [documentation](https://developers.braintreepayments.com/javascript+node/reference/request/payment-method/create#options.fail_on_duplicate_payment_method) for `failOnDuplicatePaymentMethod` is the merchant's vault, which includes all customers, so if any customer has that credit card and `failOnDuplicatePaymentMethod: true` is passed as an option, it will fail with an error.

If you purge your sandbox and then try again, the payment method will be created the first time (since the existing card has been cleared) and not the second, since it was just added.

**Comment by rkelly92** [comment]
Thanks for clarifying that. Misinterpreted the docs.
