### ISSUE TITLE
confusing type of ID parameter.

### ISSUE THREAD

**Issue by MardariG** [braintree/braintree_node#75]
gateway.customer.find(id),  the type of id must be string, it will fail if id will be type of number. However 'gateway.customer.update(id)' seems to work fine in both cases. 

version - braintree-2.23.0.min.js

Thanks.

**Comment by crookedneighbor** [comment]
I assume the braintree version you posted is for [braintree-web](https://www.npmjs.com/package/braintree-web) (the frontend javascript component) and I'm going to assume you're using the latest version of the Braintree node library (1.37.1).

The reason this is happening is because `customer.find` immediately calls the callback with a notfound error if an [empty string or blank space is submitted in the query](https://github.com/braintree/braintree_node/blob/34e3e2b4e76317799614f3a2777da41c9421db3b/src/braintree/customer_gateway.coffee#L19). It does this by calling `.trim()` on the id. Since numbers don't have a trim method, it errors. 

For `customer.update`, it  just [passes the value into the url](https://github.com/braintree/braintree_node/blob/34e3e2b4e76317799614f3a2777da41c9421db3b/src/braintree/customer_gateway.coffee#L29), and the interpolation converts it to a string automatically.

We're going to discuss internally what the best solution will be. Thanks for bringing it up!

**Comment by MardariG** [comment]
Yeah, my bad, node-js braintree version is: "braintree": "^1.37.0".

**Comment by pblesi** [comment]
@MardariG the fact that the `customer.update` method accepts a number is a coincidental behavior and not the intended behavior. Our API expects Strings unless otherwise specified.

As you can see in the example posted in our [documentation](https://developers.braintreepayments.com/reference/request/customer/find/node), a String is passed to the `customer.find` method.

To resolve your issue, be sure to convert the value to a String before you pass it to `customer.find`. This will additionally ensure that your have equality when checking values returned from Braintree, which come back as Strings and not as numbers.

Thanks!
