### ISSUE TITLE
I read the docs but not fully understand on how to do a direct payment.

### ISSUE THREAD

**Issue by kacak9229** [braintree/braintree_node#84]
Technically this is my logic when it comes to payment. Simply enter the debit/card , month/year and CVC then send to the server along with the hidden token

With braintree, Im not so sure on how to achieve the same goal, the code says about nonce and I don't really get it, I even read the docs but couldn't grasp the idea

```
var util = require('util'),
    braintree = require('braintree');
 
var gateway = braintree.connect({
  environment: braintree.Environment.Sandbox,
  merchantId: 'your_merchant_id',
  publicKey: 'your_public_key',
  privateKey: 'your_private_key'
});
 
gateway.transaction.sale({
  amount: '5.00',
  paymentMethodNonce: "nonce-from-the-client",
  options: {
    submitForSettlement: true
  }
},
  function(err, result) {
    if (result) {
      if (result.success) {
        console.log("Transaction ID: " + result.transaction.id)
      } else {
        console.log(result.message)
      }
    } else {
      console.log(err)
    }
});
```

Where is the part where I add the credit/debit card?

**Comment by jackellenberger** [comment]
Hi @kacak9229,

I would suggest you take another look at the [Braintree Overview](https://developers.braintreepayments.com/start/overview) and its child pages to get a general understanding of how interactions with Braintree are structured. We also have an [example implementation](https://github.com/braintree/braintree_express_example) in Node, which might also be helpful. 

An explanation of how a Braintree integrations function is available pictographically [here](https://developers.braintreepayments.com/start/overview#how-it-works). The code you posted is an example of the server-side half only, which is why there is nowhere to enter credit card information. That information is gathered in the client and sent to Braintree, which validates it before returning a Nonce that your server can store safely and execute transactions against. 

Because your question does not pertain specifically to the node library, I am going to go ahead and close this issue. Reach out to [Braintree support](support@braintreepayments) if you have trouble setting up your integration.
