### ISSUE TITLE
Update subscription that is already cancelled - Does not throw err

### ISSUE THREAD

**Issue by whnunlife** [braintree/braintree_node#87]
Ver: 1.41.0
Using sandbox

When calling gateway.subscription.update on a subscription that has already been cancelled, does not throw the proper err. 

The err comes back, but it's in the "result" 

```
gateway.subscription.update(user.braintree.subscriptionId, {
    planId: subscription.braintreePlanId,
    paymentMethodToken: user.braintree.token,
    price: subscription.cost
}, function (err, result) {
    console.log('err: ', err); // Err is equal to null

    if (err) {
        console.log('Err type: ', err.type);
        return callback(err);
    }

    console.log('Result: ', result); // Result contains the error message

    user.braintree.subscriptionId = result.subscription.id;

    callback(null);
});
```

Here is a sample of "result" when I console log it:

```ErrorResponse {
  errors:
   ValidationErrorsCollection {
     validationErrors: {},
     errorCollections: { subscription: [Object] } },
  params:
   { planId: 'beginner',
     paymentMethodToken: '6t3rhm',
     price: '9.99' },
  message: 'Cannot edit a canceled subscription.',
  success: false }```

**Comment by jackellenberger** [comment]
Hi @whnunlife,

It is a bit confusing, but this is the expected behavior. The `err` callback is populated when an error is encountered with the execution of the function, such as when an undefined object is passed as a parameter. What you encountered was an [Error Result](https://developers.braintreepayments.com/reference/general/result-objects/node#error-results) from the Gateway, meaning your request was syntactically valid, but rejected based on content (in this case, attempting to update and expired subscription).

**Comment by whnunlife** [comment]
@jackellenberger Gotcha, that makes sense.
